import Main from '../../components/Main';
import Head from 'next/head'
import About from '../../components/About'
import Skills from 'components/Skills';
import Projects from 'components/Projects';
import Contact from 'components/Contact';


export default function Home() {
  return (
    <>
      <Head>
        <title>Keith | Full Stack Developer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/favicon.ico" />
      </Head>
      <Main />
      <About/>
      <Skills/>
      <Projects/>
      <Contact/>
    </>
  )
}
